import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { birthdayName } from "@/store/data/data";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Happy birthday {birthdayName}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={styles.section}>
        <figure className={styles.figure}>
          <div className={styles.cardFront}>Mi amorcita </div>
          <div className={styles.cardBack}></div>
        </figure>
      </section>
    </>
  );
}
